dist: xenial
language: node_js
sudo: false
services:
    - mysql
node_js:
    - 10
    - 11
install:
    - npm install
    - npm install -g ts-node
    - ts-node ./src/commands/generate-private-keys.ts
before_script:
    - wget https://repo.mysql.com//mysql-apt-config_0.8.10-1_all.deb
    - sudo dpkg -i mysql-apt-config_0.8.10-1_all.deb
    - sudo apt-get update -q
    - sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew mysql-server
    - sudo systemctl restart mysql
    - sudo mysql_upgrade
    - mysql --version
script:
    - npm run travis-ci-test -- --coverage
    - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
