language: node_js
sudo: false
services:
    - mysql
node_js:
    - 10
    - 11
install:
    - npm install
    - npm install -g ts-node
    - ts ./src/commands/generate-private-keys.ts
script:
    - npm run travis-ci-test -- --coverage
